import type { Address } from 'viem'
import { useReadContract } from 'wagmi'

import { THEMIS_HOOK_ABI } from './abis'

// ─── Deployed on Ethereum Sepolia (chain 11155111) ────────────────────────────
// Source of truth: ../deployments/11155111.json (regenerated by script/00_DeployThemis.s.sol
// and script/01_CreatePoolAndAddLiquidity.s.sol — keep these in sync with that file).

export const CONTRACTS = {
  HOOK: '0xa4FC05B84A363c5118E2454D3c1E15aBB0FA0044' as Address,
  VAULT: '0x9F0d36DFf418195F767763B17B5D9E5782D74ED0' as Address,
  POOL_MANAGER: '0xE03A1074c86CFeDd5C142C4F04F1a1536e203543' as Address,
  SWAP_ROUTER: '0xf13D190e9117920c703d79B5F33732e10049b115' as Address,
  // TOKEN0 is native ETH — Themis pools always pair native ETH as currency0.
  TOKEN1: '0x6243d837973153B2681055D284992EBC7f02f426' as Address,
} as const

export const NATIVE_ETH = '0x0000000000000000000000000000000000000000' as Address

export const POOL_ID = '0x10ac9ee266c2bbd419011b1bd6d423803a466ed2df6bf75f15ce375b327e5a62' as `0x${string}`

// PoolKey struct — matches what was used to create the pool.
export const POOL_KEY = {
  currency0: NATIVE_ETH,
  currency1: CONTRACTS.TOKEN1,
  fee: 500,
  tickSpacing: 10,
  hooks: CONTRACTS.HOOK,
} as const

export const REGIME_LABELS = ['GREEN', 'AMBER', 'RED'] as const

/// Preview the risk score/regime/premium a swap would trigger, without sending it.
/// zeroForOne=true means ETH -> TOKEN1 — the only direction the swap page drives.
export function usePreviewRisk(zeroForOne: boolean, amountSpecified: bigint) {
  const { data, isLoading, error } = useReadContract({
    address: CONTRACTS.HOOK,
    abi: THEMIS_HOOK_ABI,
    functionName: 'previewRisk',
    args: [POOL_ID, zeroForOne, -amountSpecified], // exact-input: negative per IPoolManager convention
    query: { enabled: amountSpecified > 0n },
  })

  const [riskScore, regime, premiumPpm] = data ?? [0, 0, 0]

  return { score: riskScore, regime, premiumPpm, isLoading, error }
}
