import { useEffect, useState } from 'react'
import type { Address, PublicClient } from 'viem'
import { useReadContract, useReadContracts, usePublicClient } from 'wagmi'

import { FAIR_SHARE_VAULT_ABI, STATE_VIEW_ABI, THEMIS_HOOK_ABI } from './abis'

// ─── Deployed on Ethereum Sepolia (chain 11155111) ────────────────────────────
// Source of truth: ../deployments/11155111.json (regenerated by script/00_DeployThemis.s.sol
// and script/01_CreatePoolAndAddLiquidity.s.sol — keep these in sync with that file).

export const CONTRACTS = {
  HOOK: '0xa4FC05B84A363c5118E2454D3c1E15aBB0FA0044' as Address,
  VAULT: '0x9F0d36DFf418195F767763B17B5D9E5782D74ED0' as Address,
  POOL_MANAGER: '0xE03A1074c86CFeDd5C142C4F04F1a1536e203543' as Address,
  SWAP_ROUTER: '0xf13D190e9117920c703d79B5F33732e10049b115' as Address,
  // Uniswap's official v4 StateView periphery contract on Sepolia — a read-only
  // lens over PoolManager's extsload-only storage (getSlot0, getLiquidity).
  STATE_VIEW: '0xe1dd9c3fa50edb962e442f60dfbc432e24537e4c' as Address,
  // TOKEN0 is native ETH — Themis pools always pair native ETH as currency0.
  TOKEN1: '0x6243d837973153B2681055D284992EBC7f02f426' as Address,
} as const

export const NATIVE_ETH = '0x0000000000000000000000000000000000000000' as Address

export const POOL_ID = '0x10ac9ee266c2bbd419011b1bd6d423803a466ed2df6bf75f15ce375b327e5a62' as `0x${string}`

// Block script/00_DeployThemis.s.sol landed at — the earliest block any Themis
// event could exist, so log queries never need to scan further back than this.
export const DEPLOYMENT_BLOCK = 11531145n

// PoolKey struct — matches what was used to create the pool.
export const POOL_KEY = {
  currency0: NATIVE_ETH,
  currency1: CONTRACTS.TOKEN1,
  fee: 500,
  tickSpacing: 10,
  hooks: CONTRACTS.HOOK,
} as const

// Full-range tick bounds for tickSpacing=10 (TickMath.minUsableTick/maxUsableTick),
// and their sqrtPriceX96 — fixed constants, since every Themis pool uses full-range
// liquidity (see script/01_CreatePoolAndAddLiquidity.s.sol).
const SQRT_PRICE_MIN = 4295558252n
const SQRT_PRICE_MAX = 1461300573427867316570072651998408279850435624081n
const Q96 = 1n << 96n

export const REGIME_LABELS = ['GREEN', 'AMBER', 'RED'] as const

/// Preview the risk score/regime/premium a swap would trigger, without sending it.
/// zeroForOne=true means ETH -> TOKEN1 — the only direction the swap page drives.
export function usePreviewRisk(zeroForOne: boolean, amountSpecified: bigint) {
  const { data, isLoading, error } = useReadContract({
    address: CONTRACTS.HOOK,
    abi: THEMIS_HOOK_ABI,
    functionName: 'previewRisk',
    args: [POOL_ID, zeroForOne, -amountSpecified], // exact-input: negative per IPoolManager convention
    query: { enabled: amountSpecified > 0n },
  })

  const [riskScore, regime, premiumPpm] = data ?? [0, 0, 0]

  return { score: riskScore, regime, premiumPpm, isLoading, error }
}

/// TVL for the Themis pool, read live via StateView. Since the pool is always
/// full-range (see POOL_KEY / SQRT_PRICE_MIN/MAX above), the current price is
/// guaranteed to sit between the bounds, so this always takes the same branch
/// LiquidityAmounts.getAmountsForLiquidity would — no need for the general
/// three-branch logic a partial-range position would require.
export function useTvl() {
  const { data, isLoading, error } = useReadContracts({
    contracts: [
      { address: CONTRACTS.STATE_VIEW, abi: STATE_VIEW_ABI, functionName: 'getSlot0', args: [POOL_ID] },
      { address: CONTRACTS.STATE_VIEW, abi: STATE_VIEW_ABI, functionName: 'getLiquidity', args: [POOL_ID] },
    ],
  })

  if (!data?.[0]?.result || !data[1]?.result) {
    return { amount0: 0n, amount1: 0n, isLoading, error }
  }

  const [sqrtPriceX96] = data[0].result
  const liquidity = data[1].result

  // getAmount0ForLiquidity(sqrtPriceX96, SQRT_PRICE_MAX, liquidity)
  const amount0 = ((liquidity << 96n) * (SQRT_PRICE_MAX - sqrtPriceX96)) / SQRT_PRICE_MAX / sqrtPriceX96
  // getAmount1ForLiquidity(SQRT_PRICE_MIN, sqrtPriceX96, liquidity)
  const amount1 = (liquidity * (sqrtPriceX96 - SQRT_PRICE_MIN)) / Q96

  return { amount0, amount1, isLoading, error }
}

const LOG_CHUNK_BLOCKS = 5000n // conservative — stays under most public RPCs' per-call range caps

async function getEventsChunked(
  publicClient: PublicClient,
  params: { address: Address; abi: readonly unknown[]; eventName: string; args?: Record<string, unknown> },
  fromBlock: bigint,
  toBlock: bigint,
) {
  const logs = []
  for (let start = fromBlock; start <= toBlock; start += LOG_CHUNK_BLOCKS + 1n) {
    const end = start + LOG_CHUNK_BLOCKS > toBlock ? toBlock : start + LOG_CHUNK_BLOCKS
    // Sequential, not Promise.all — stays gentle on public RPC rate limits.
    const chunk = await publicClient.getContractEvents({ ...params, fromBlock: start, toBlock: end })
    logs.push(...chunk)
  }
  return logs
}

export interface PoolStats {
  cumulativeRiskPremiumDiverted0: bigint
  cumulativeRiskPremiumDiverted1: bigint
  cumulativeFairShareReceived: bigint
  cumulativeFairShareDistributed0: bigint
  cumulativeFairShareDistributed1: bigint
  swapCounts: { green: number; amber: number; red: number }
  isLoading: boolean
  error: Error | null
}

const EMPTY_STATS: PoolStats = {
  cumulativeRiskPremiumDiverted0: 0n,
  cumulativeRiskPremiumDiverted1: 0n,
  cumulativeFairShareReceived: 0n,
  cumulativeFairShareDistributed0: 0n,
  cumulativeFairShareDistributed1: 0n,
  swapCounts: { green: 0, amber: 0, red: 0 },
  isLoading: true,
  error: null,
}

/// Cumulative on-chain stats, aggregated client-side from event logs between
/// DEPLOYMENT_BLOCK and the current block. No on-chain running-total counter
/// exists for these (aside from the vault's pending/distributed mappings,
/// which only cover one currency-pair snapshot, not a full history) — reading
/// the events themselves is the direct, literal on-chain source of truth.
export function usePoolStats(): PoolStats {
  const publicClient = usePublicClient()
  const [stats, setStats] = useState<PoolStats>(EMPTY_STATS)

  useEffect(() => {
    if (!publicClient) return
    let cancelled = false

    async function run() {
      try {
        const latest = await publicClient!.getBlockNumber()

        const [premiumLogs, receivedLogs, distributedLogs, swapLogs] = await Promise.all([
          getEventsChunked(
            publicClient!,
            { address: CONTRACTS.HOOK, abi: THEMIS_HOOK_ABI, eventName: 'RiskPremiumDiverted', args: { poolId: POOL_ID } },
            DEPLOYMENT_BLOCK,
            latest,
          ),
          getEventsChunked(
            publicClient!,
            { address: CONTRACTS.VAULT, abi: FAIR_SHARE_VAULT_ABI, eventName: 'FairShareReceived' },
            DEPLOYMENT_BLOCK,
            latest,
          ),
          getEventsChunked(
            publicClient!,
            { address: CONTRACTS.VAULT, abi: FAIR_SHARE_VAULT_ABI, eventName: 'FairShareDistributed', args: { poolId: POOL_ID } },
            DEPLOYMENT_BLOCK,
            latest,
          ),
          getEventsChunked(
            publicClient!,
            { address: CONTRACTS.HOOK, abi: THEMIS_HOOK_ABI, eventName: 'ThemisSwapObserved', args: { poolId: POOL_ID } },
            DEPLOYMENT_BLOCK,
            latest,
          ),
        ])

        let premium0 = 0n
        let premium1 = 0n
        for (const log of premiumLogs) {
          const { currency, amount } = (log as unknown as { args: { currency: Address; amount: bigint } }).args
          if (currency.toLowerCase() === NATIVE_ETH) premium0 += amount
          else premium1 += amount
        }

        const received = receivedLogs.reduce(
          (sum, log) => sum + (log as unknown as { args: { amount: bigint } }).args.amount,
          0n,
        )

        let distributed0 = 0n
        let distributed1 = 0n
        for (const log of distributedLogs) {
          const { amount0, amount1 } = (log as unknown as { args: { amount0: bigint; amount1: bigint } }).args
          distributed0 += amount0
          distributed1 += amount1
        }

        const swapCounts = { green: 0, amber: 0, red: 0 }
        for (const log of swapLogs) {
          const { regime } = (log as unknown as { args: { regime: number } }).args
          if (regime === 0) swapCounts.green++
          else if (regime === 1) swapCounts.amber++
          else swapCounts.red++
        }

        if (!cancelled) {
          setStats({
            cumulativeRiskPremiumDiverted0: premium0,
            cumulativeRiskPremiumDiverted1: premium1,
            cumulativeFairShareReceived: received,
            cumulativeFairShareDistributed0: distributed0,
            cumulativeFairShareDistributed1: distributed1,
            swapCounts,
            isLoading: false,
            error: null,
          })
        }
      } catch (err) {
        if (!cancelled) setStats((s) => ({ ...s, isLoading: false, error: err as Error }))
      }
    }

    run()
    return () => {
      cancelled = true
    }
  }, [publicClient])

  return stats
}
